name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pylint pytest pytest-cov

    - name: Debug directory contents
      run: |
        pwd
        ls -la

    - name: Run pylint
      run: |
        pylint *.py --fail-under=8

    - name: Run tests with coverage
      run: |
        pytest test.py --cov=./ --cov-report=xml

    - name: Verify coverage file
      run: |
        ls -la coverage.xml || echo "coverage.xml not found"

    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false  # Changed to false to avoid pipeline failure
